### ISSUE TITLE
Should functions like {a}_as_{b} be changed to {a}_to_{b} ?

### ISSUE THREAD

**Issue by fhightower** [democritus-project/roadmap#41]
For example, should `domain_as_punycode` be changed to `domain_to_punycode`?

**Comment by raprocks** [comment]
actually i think the prior one is better to understand. so lets keep it the same unless obviously you have some other opinions

**Comment by fhightower** [comment]
Sounds good we'll keep that. Thanks for the input and sorry it's taken me so long to respond (had some busy life circumstances recently).
